using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace ReportingService.Infrastructure.Export
{
    public class PdfExportService
    {
        public string GeneratePdf(string filePath, Guid planningId, string generatedBy)
{
    QuestPDF.Settings.License = LicenseType.Community;

    Document.Create(container =>
    {
        container.Page(page =>
        {
            page.Margin(40);
            page.Header().Text("ShiftMaster - Official Report").FontSize(25).Bold();

            page.Content().Column(column =>
            {
                column.Item().Text($"Planning ID: {planningId}"); // Maintenant il le connaît
                column.Item().Text($"Generated At: {DateTime.UtcNow}");
                column.Item().Text($"Generated By: {generatedBy}"); // Maintenant il le connaît
            });

            page.Footer().AlignCenter().Text("Confidential - RH Department");
        });
    })
    .GeneratePdf(filePath);

    return filePath;
}
        
    }
}
